; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino


; Velocidad del puerto serial (para ver los mensajes rápido)
monitor_speed = 115200

; Velocidad de subida del firmware (para no esperar años)
upload_speed = 921600

; Velocidad para recibir los reportes de test
test_speed = 115200  

test_build_src = true

; 2. Filtros del Monitor 
; send_on_enter: No envía nada hasta dar Enter.
; time: Muestra la hora en cada mensaje (útil para debug).
; colorize: Colores si se usan logs con formato.
monitor_filters = 
    send_on_enter
    time
    colorize

; 3. Ver lo que escribo
monitor_echo = yes

; 4. Forzar el salto de línea al enviar
; Esto asegura que cuando se de Enter, se envíe \n (LF) o \r\n (CRLF)
monitor_eol = LF

; Habilitar herramienta de chequeo
check_tool = cppcheck

check_skip_packages = yes

; Configuración de severidad (quiero que sea estricto)
check_flags =
  cppcheck: --enable=all --inline-suppr --suppress=missingIncludeSystem